### ISSUE TITLE
Bill Attachment Functionality Required

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/SiteExpense_module#5]
@RajeevKumarmbd Provide **Upload Attachment** option in Expense Voucher screen
1) In siteexpdommodule_amountspenttable Model python file add following code (change it to make it compatible for Odoo 12, the code pasted below is of lower version
import urllib

attachment = fields.Char('Attachments',compute='_urlGen')
    
@api.depends('name')
def _urlGen(self):
        index = (self.defaultproject or '') + '_' + (self.name or '')
        args = {"AthHandle" : "J_SITE_EXPENSE",
                "Index": index, "AttachedBy" : defaultsiteincharge, "ed" : "y"}
        url = "http://192.9.200.146/Attachment/Attachment.aspx?{}".format(urllib.urlencode(args))
        self.attachment = url

2) In siteexpdommodule_amountspenttable  View 
<field name="attachment" widget="url" nolabel="1" text="Attachments"/>

@veena-isgec Provide Attachment Handle  J_SITE_EXPENSE, Index: PROJECTCODE_VOUCHERNO

**Comment by veena-isgec** [comment]
done
